name: Run JavaScript File
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run JavaScript file
        run: node FacebookAds.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add facebook_ads_data.txt
          git commit -m "Update live_events.m3u8" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF} || echo "No changes to push"
